site_name: outline-vpn-api-client
site_url: https://outline-vpn-api-client.readthedocs.io/en/latest/
repo_url: https://github.com/Zeph1rr/outline-vpn-api-client
repo_name: Zeph1rr/outline-vpn-api-client

theme:
  name: material
  palette:
    primary: indigo
  language: en

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference:
    - Sync:
      - OutlineClient: api/client.md
      - AccessKeys: api/access_keys.md
      - Metrics: api/metrics.md
      - Server: api/server.md
    - Async:
      - AsyncOutlineClient: api/async_client.md
      - AsyncAccessKeys: api/async_access_keys.md
      - AsyncMetrics: api/async_metrics.md
      - AsyncServer: api/async_server.md
    - Models: api/models.md

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          nav_translations:
            Home: Главная
            Usage: Использование
            API Reference: Справочник API
            Sync: Синхронный
            Async: Асинхронный
            Models: Модели
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google