name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Configure SSH key
        env:
          PRIVATE_KEY: ${{ secrets.ID_RSA }}
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Проверка валидности ключа
          ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null || (echo "Invalid private key" && exit 1)
          # Добавление хоста в known_hosts
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Run tests
        env:
          SSH_HOST: ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
        run: |
          poetry run pytest -v --cov-report term --cov=outline_vpn_api_client tests/
